### ISSUE TITLE
title of the text field not mentioned

### ISSUE THREAD

**Issue by rishimadan14** [aniruddh622003/upes_parikshamitr_teacher_frontend#20]
page where issue occurred: mark attendance 
Steps to Reproduce: invigilation dashboard-> seating arrangement-> mark attendance
Expected result: It should show the indication of what text field is and what to enter
Actual result: only text box. no naming
Severity - minor/major/critical: critical
Additional notes: fix please
![WhatsApp Image 2024-03-09 at 16 41 16_2dc0159a](https://github.com/aniruddh622003/upes_parikshamitr_teacher_frontend/assets/76414582/2aa44aea-aaee-46cb-8b28-72bc482d5c36)

**Comment by aniruddh622003** [comment]
Design issue. The designer reported this bug and then changed the design.

**Comment by aniruddh622003** [comment]
@rishimadan14 design is not up to the mark.
Alignment is off and titles does not follow the app theme

![Screenshot_20240309-172622](https://github.com/aniruddh622003/upes_parikshamitr_teacher_frontend/assets/32842941/4807a6c0-0fff-421c-9efa-bbc5eb5e5e0e)

**Comment by rishimadan14** [comment]
updated the alignment

**Comment by EshanDutta10** [comment]
![image](https://github.com/aniruddh622003/upes_parikshamitr_teacher_frontend/assets/63641401/521917cd-7aee-447b-aae5-e870106cae04)

fixed.
